"""
This type stub file was generated by pyright.
"""

from .image_processing_conditional_detr import ConditionalDetrImageProcessor

"""Feature extractor class for Conditional DETR."""
logger = ...

def rgb_to_id(x):  # -> NDArray[signedinteger[Any]] | NDArray[signedinteger[_32Bit]] | NDArray[Any] | int:
    ...

class ConditionalDetrFeatureExtractor(ConditionalDetrImageProcessor):
    def __init__(self, *args, **kwargs) -> None: ...

__all__ = ["ConditionalDetrFeatureExtractor"]
