"""
This type stub file was generated by pyright.
"""

logger = ...
DEFAULT_SYSTEM_MESSAGE = ...
DEFAULT_VIDEO_INTRO = ...
DEFAULT_MEDIA_OUTTRO = ...
FRAME_TIMESTAMP_MESSAGE = ...

def smolvlm_sample_indices_fn(metadata, max_frames, target_fps, skip_secs=...):  # -> NDArray[Any]:
    """
    Example sampling function which:
      - Uses `max_frames` (if provided) or calculates it from `fps` and metadata.
      - Applies a basic center-skip if fewer frames than available, otherwise
        optionally skips `skip_secs` from both the start and end.
      - Uniformly samples the desired number of frames between the start and end indices.

    Args:
        max_frames (`int`):
            Maximum number of frames to sample.
        target_fps (`int`):
            Target frames to sample per second.
        metadata (`dict`):
            Contains video metadata such as "n_frames" and "video_fps".
        skip_secs (`float`, *optional*, defaults to 1.0):
            Number of seconds to skip from the start and end if the video is long enough.

    Returns:
        numpy.ndarray:
            An array of unique frame indices to sample.
    """
    ...
