"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from .tokenization_code_llama import *
from .tokenization_code_llama_fast import *

if TYPE_CHECKING: ...
else: ...
