"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from .configuration_idefics2 import *
from .image_processing_idefics2 import *
from .modeling_idefics2 import *
from .processing_idefics2 import *

if TYPE_CHECKING: ...
else: ...
