"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from .configuration_biogpt import *
from .modeling_biogpt import *
from .tokenization_biogpt import *

if TYPE_CHECKING: ...
else: ...
