"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from .configuration_granitemoeshared import *
from .modeling_granitemoeshared import *

if TYPE_CHECKING: ...
else: ...
