"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from .configuration_trocr import *
from .modeling_trocr import *
from .processing_trocr import *

if TYPE_CHECKING: ...
else: ...
