"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from .configuration_bigbird_pegasus import *
from .modeling_bigbird_pegasus import *

if TYPE_CHECKING: ...
else: ...
