"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from .configuration_idefics3 import *
from .image_processing_idefics3 import *
from .modeling_idefics3 import *
from .processing_idefics3 import *

if TYPE_CHECKING: ...
else: ...
