"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from .configuration_depth_anything import *
from .modeling_depth_anything import *

if TYPE_CHECKING: ...
else: ...
